import type { BlogPost } from "./posts";

type Topic = {
  date: string; slug: string; title: string; category: string; audience: string;
  objective: string; tactics: string[]; metrics: string[];
};

const topics: Topic[] = [
  { date:"2026-08-23", slug:"catering-menu-pricing-for-restaurants", title:"Catering Menu Pricing for Restaurants: A Profitable Framework", category:"Menu strategy", audience:"restaurant owners building or revising a catering menu", objective:"price packages that remain attractive to buyers while protecting food, labor, packaging, and delivery margin", tactics:["Cost every package at realistic serving sizes","Separate delivery and service charges clearly","Use profitable add-ons to increase order value","Review actual margin after every large order"], metrics:["food-cost percentage","contribution margin","average order value","discount rate"] },
  { date:"2026-08-24", slug:"corporate-catering-lead-generation", title:"Corporate Catering Lead Generation for Local Restaurants", category:"Demand generation", audience:"operators seeking qualified local business accounts", objective:"build a repeatable pipeline of office, medical, education, and event buyers", tactics:["Define a profitable delivery radius","Build a list by account type and order potential","Use relevant outreach instead of generic blasts","Record every response and next action"], metrics:["qualified leads","reply rate","meetings booked","first orders"] },
  { date:"2026-08-25", slug:"catering-order-checklist", title:"The Restaurant Catering Order Checklist: From Inquiry to Delivery", category:"Operations", audience:"teams that need fewer mistakes on scheduled group orders", objective:"create a reliable handoff from sales through kitchen production, packing, dispatch, and follow-up", tactics:["Confirm guest count and dietary needs","Lock production and packing deadlines","Assign one delivery owner","Complete a final order audit before dispatch"], metrics:["order accuracy","on-time delivery","refund rate","customer satisfaction"] },
  { date:"2026-08-26", slug:"increase-catering-average-order-value", title:"How to Increase Catering Average Order Value Without Heavy Discounting", category:"Growth strategy", audience:"restaurants that want more revenue from each catering customer", objective:"increase useful order value through better packages, add-ons, and buyer guidance", tactics:["Bundle complete meal solutions","Offer beverages, desserts, and serviceware","Use serving guidance to prevent under-ordering","Set sensible delivery minimums"], metrics:["average order value","items per order","add-on attachment rate","gross margin"] },
  { date:"2026-08-27", slug:"restaurant-catering-delivery-zones", title:"How Restaurants Should Set Catering Delivery Zones and Fees", category:"Delivery operations", audience:"operators balancing reach, reliability, and delivery economics", objective:"define delivery rules that protect punctuality and profit", tactics:["Map drive time by daypart","Create distance or time-based zones","Set order minimums by zone","Price extraordinary access and wait time"], metrics:["delivery cost per order","on-time rate","miles per delivery","delivery margin"] },
  { date:"2026-08-28", slug:"catering-packaging-guide", title:"Catering Packaging: A Practical Guide for Restaurant Operators", category:"Operations", audience:"restaurants improving food quality and presentation in transit", objective:"select packaging that protects temperature, appearance, portioning, and setup", tactics:["Test packaging under real drive times","Label every package consistently","Separate hot, cold, and fragile items","Standardize serviceware quantities"], metrics:["packaging cost","damage rate","missing-item rate","customer feedback"] },
  { date:"2026-08-29", slug:"convert-catering-inquiries-into-orders", title:"How to Convert More Catering Inquiries Into Confirmed Orders", category:"Sales process", audience:"restaurant teams responding to catering leads", objective:"reduce response time and make the buying decision easier", tactics:["Reply with a clear next step","Use packages matched to the event","State availability, fees, and deadlines upfront","Follow up before the buyer's decision date"], metrics:["first-response time","quote conversion","follow-up completion","lost-lead reasons"] },
  { date:"2026-08-30", slug:"catering-menu-design-for-travel", title:"How to Design a Restaurant Catering Menu That Travels Well", category:"Menu strategy", audience:"chefs and operators adapting dine-in food for group delivery", objective:"build a focused menu that holds quality during production, transport, and service", tactics:["Choose dependable high-volume items","Test hold time and texture","Simplify risky modifiers","Document portions and plating instructions"], metrics:["production time","waste","quality complaints","menu-item margin"] },
  { date:"2026-08-31", slug:"catering-repeat-orders", title:"How to Turn First-Time Catering Buyers Into Repeat Accounts", category:"Customer retention", audience:"restaurants pursuing predictable recurring catering revenue", objective:"create a structured post-order and reorder process", tactics:["Follow up within one business day","Save account and dietary preferences","Ask about recurring meetings","Send relevant reorder reminders"], metrics:["repeat-order rate","days to reorder","account revenue","retention rate"] },
  { date:"2026-09-01", slug:"restaurant-catering-seo", title:"Restaurant Catering SEO: A Local Search Playbook", category:"Demand generation", audience:"restaurants that want qualified catering traffic from search", objective:"make catering services discoverable for high-intent local searches", tactics:["Create a dedicated catering landing page","Publish useful city-specific information","Strengthen internal links and business details","Earn relevant local mentions and reviews"], metrics:["non-brand impressions","qualified organic visits","form submissions","organic orders"] },
  { date:"2026-09-02", slug:"catering-production-planning", title:"Catering Production Planning for Busy Restaurant Kitchens", category:"Kitchen operations", audience:"kitchens balancing regular service with scheduled large orders", objective:"plan labor, prep, equipment, and staging without disrupting core service", tactics:["Translate orders into batch quantities","Set prep and cook milestones","Reserve equipment and staging space","Assign a final production lead"], metrics:["labor hours","production variance","late orders","waste"] },
  { date:"2026-09-03", slug:"catering-sales-funnel", title:"Building a Measurable Catering Sales Funnel for Restaurants", category:"Sales process", audience:"owners who need visibility from lead to repeat customer", objective:"define each stage and the action required to advance qualified opportunities", tactics:["Use consistent lead stages","Record value and decision date","Assign an owner to every opportunity","Review stalled leads weekly"], metrics:["stage conversion","pipeline value","sales cycle","win rate"] },
  { date:"2026-09-04", slug:"catering-food-cost-control", title:"Catering Food-Cost Control Without Compromising Guest Experience", category:"Profitability", audience:"operators protecting margin on large-format orders", objective:"reduce cost variance while keeping portions and presentation dependable", tactics:["Use tested batch recipes","Standardize serving utensils","Track substitutions and waste","Compare estimated and actual usage"], metrics:["food-cost variance","waste percentage","portion variance","contribution margin"] },
  { date:"2026-09-05", slug:"catering-dietary-requirements", title:"Managing Allergies and Dietary Requirements in Catering Orders", category:"Operations", audience:"teams handling group orders with mixed dietary needs", objective:"capture, communicate, and label dietary information consistently", tactics:["Ask structured dietary questions","Separate allergy notes from preferences","Use clear package labels","Confirm limitations with the customer"], metrics:["label accuracy","dietary-related errors","clarification time","complaints"] },
  { date:"2026-09-06", slug:"office-catering-packages", title:"Office Catering Packages That Make Ordering Easier", category:"Menu strategy", audience:"restaurants serving workplace meetings and events", objective:"offer complete, easy-to-compare packages for common office occasions", tactics:["Organize packages by occasion","Show servings and dietary choices","Include logical add-ons","Make setup requirements explicit"], metrics:["package conversion","average order value","ordering time","add-on rate"] },
  { date:"2026-09-07", slug:"catering-customer-service-recovery", title:"Catering Service Recovery: What to Do When an Order Goes Wrong", category:"Customer experience", audience:"managers responsible for high-stakes catering relationships", objective:"resolve failures quickly and protect customer trust", tactics:["Acknowledge the issue immediately","Offer a practical same-day remedy","Document the root cause","Follow up after resolution"], metrics:["resolution time","refund cost","customer retention","repeat failures"] },
  { date:"2026-09-08", slug:"catering-staff-training", title:"Restaurant Catering Staff Training: Roles, Standards, and Checklists", category:"Team operations", audience:"restaurants building a dependable catering team", objective:"give every employee clear responsibilities and measurable standards", tactics:["Define ownership by order stage","Train with realistic scenarios","Use packing and dispatch checklists","Coach from weekly performance reviews"], metrics:["training completion","order errors","labor efficiency","on-time rate"] },
  { date:"2026-09-09", slug:"catering-quote-template", title:"What Every Restaurant Catering Quote Should Include", category:"Sales process", audience:"teams creating proposals for business and event buyers", objective:"produce clear quotes that reduce uncertainty and speed approval", tactics:["Summarize event details","Itemize packages, fees, and taxes","State payment and change deadlines","Include one clear acceptance step"], metrics:["quote turnaround","approval rate","revision count","payment speed"] },
  { date:"2026-09-10", slug:"catering-capacity-planning", title:"Catering Capacity Planning: How Much Volume Can Your Restaurant Handle?", category:"Operations", audience:"owners evaluating safe catering growth", objective:"set order limits using kitchen, labor, equipment, and delivery constraints", tactics:["Measure capacity by daypart","Identify the tightest production constraint","Set cutoff rules by order complexity","Review limits after peak events"], metrics:["orders per window","capacity utilization","overtime","late fulfillment"] },
  { date:"2026-09-11", slug:"catering-payment-policies", title:"Restaurant Catering Deposits, Payments, and Cancellation Policies", category:"Profitability", audience:"operators reducing financial risk on scheduled orders", objective:"set payment rules that are fair, clear, and operationally workable", tactics:["Require deposits for qualifying orders","Set final-count deadlines","Publish cancellation terms","Use secure digital payment methods"], metrics:["deposit collection","late payments","cancellation loss","chargebacks"] },
  { date:"2026-09-12", slug:"catering-google-business-profile", title:"How to Use Google Business Profile to Promote Restaurant Catering", category:"Demand generation", audience:"local restaurants improving catering discovery", objective:"communicate catering services clearly where local customers already search", tactics:["Add accurate catering services","Publish strong food and setup photos","Link to the catering page","Request reviews from genuine catering customers"], metrics:["profile views","website clicks","calls","catering inquiries"] },
  { date:"2026-09-13", slug:"catering-order-minimums", title:"How to Set Restaurant Catering Order Minimums", category:"Profitability", audience:"restaurants deciding which orders are economically worthwhile", objective:"set minimums based on real production, packaging, administration, and delivery costs", tactics:["Calculate fixed cost per order","Separate pickup and delivery minimums","Adjust minimums by zone and peak time","Review lost demand and margin together"], metrics:["margin per order","orders below target","conversion rate","delivery cost"] },
  { date:"2026-09-14", slug:"catering-kpis-dashboard", title:"The Restaurant Catering KPI Dashboard: What to Track Weekly", category:"Performance", audience:"owners who need actionable catering visibility", objective:"focus weekly decisions on a small set of revenue, service, and margin indicators", tactics:["Use one consistent reporting period","Separate first-time and repeat buyers","Review exceptions, not just averages","Assign an action to every material variance"], metrics:["catering revenue","average order value","repeat rate","contribution margin"] },
  { date:"2026-09-15", slug:"holiday-catering-planning", title:"Holiday Catering Planning for Restaurant Operators", category:"Seasonal strategy", audience:"restaurants preparing for concentrated seasonal demand", objective:"secure profitable orders early while protecting execution during peak weeks", tactics:["Set menus and capacity before promotion","Publish cutoff dates","Prioritize repeat accounts","Build contingency plans for labor and delivery"], metrics:["booked revenue","capacity utilization","average order value","on-time delivery"] },
  { date:"2026-09-16", slug:"catering-delivery-driver-checklist", title:"The Catering Delivery Driver Checklist", category:"Delivery operations", audience:"restaurants managing their own catering deliveries", objective:"give drivers a consistent process for pickup, transport, arrival, setup, and proof of delivery", tactics:["Verify order and contact details","Protect temperature and load stability","Confirm parking and access","Record delivery completion"], metrics:["on-time arrival","missing items","driver wait time","delivery incidents"] },
  { date:"2026-09-17", slug:"catering-sales-outreach-email", title:"Restaurant Catering Outreach Emails That Respect the Buyer", category:"Demand generation", audience:"operators contacting qualified local organizations", objective:"write concise, relevant messages that start useful conversations without spam", tactics:["Lead with a specific local reason","Connect the offer to a likely need","Use one simple call to action","Stop sequences when interest is absent"], metrics:["delivery rate","positive replies","meetings","opt-outs"] },
  { date:"2026-09-18", slug:"catering-menu-photography", title:"Catering Menu Photography That Helps Buyers Order Confidently", category:"Marketing", audience:"restaurants improving catering pages and proposals", objective:"show portions, packaging, and presentation accurately enough to support a group-order decision", tactics:["Photograph complete packages","Show serving scale","Include packaged and setup views","Keep color and portions realistic"], metrics:["menu engagement","conversion rate","photo-assisted inquiries","expectation complaints"] },
  { date:"2026-09-19", slug:"catering-crm-basics", title:"Catering CRM Basics for Independent Restaurants", category:"Catering technology", audience:"restaurants organizing buyer relationships and follow-up", objective:"maintain useful account history without adding unnecessary administrative work", tactics:["Store company and contact roles","Record preferences and past orders","Schedule meaningful follow-ups","Keep ownership and next steps visible"], metrics:["follow-up completion","active accounts","repeat revenue","stale opportunities"] },
  { date:"2026-09-20", slug:"catering-profit-margin", title:"How to Calculate Catering Profit Margin Accurately", category:"Profitability", audience:"owners comparing catering revenue with true contribution", objective:"account for food, labor, packaging, delivery, discounts, and payment costs", tactics:["Cost variable inputs per order","Allocate direct catering labor","Record delivery and platform fees","Review margin by package and account"], metrics:["gross margin","contribution margin","labor percentage","delivery margin"] },
  { date:"2026-09-21", slug:"restaurant-catering-growth-plan", title:"A One-Year Restaurant Catering Growth Plan", category:"Growth strategy", audience:"operators turning early catering activity into a durable channel", objective:"sequence offer, operations, demand, retention, and measurement improvements across four quarters", tactics:["Build the operational foundation first","Acquire a focused set of local accounts","Systemize repeat-order activity","Scale only after service and margin targets hold"], metrics:["annual catering revenue","active accounts","repeat rate","contribution margin"] }
];

function makePost(topic: Topic): BlogPost {
  const list = topic.tactics.join(", ");
  return {
    slug: topic.slug,
    title: topic.title,
    description: `A practical guide for ${topic.audience} to ${topic.objective}.`,
    date: topic.date,
    readTime: "7 min read",
    category: topic.category,
    intro: `For ${topic.audience}, the goal is not activity for its own sake. The goal is to ${topic.objective}. A dependable approach connects the customer promise to clear ownership, realistic economics, and consistent execution.`,
    sections: [
      { heading: "Start with the operating goal", paragraphs: [`Define the result before choosing tactics or tools. In this case, the practical objective is to ${topic.objective}. Write down the current process, the owner of each handoff, and the constraints that could affect the customer experience.`] },
      { heading: "Build the core process", paragraphs: [`A strong first version should be simple enough for the team to repeat during a busy service. Focus on the few actions that materially improve reliability and buyer confidence.`], bullets: topic.tactics },
      { heading: "Put the process into practice", paragraphs: [`Test the workflow with one realistic order or account before expanding it. Assign an owner, define a deadline, and capture exceptions while they are still fresh. The working checklist should reflect what the restaurant can execute consistently—not an idealized process that disappears during peak periods.`] },
      { heading: "Common mistakes to avoid", paragraphs: [`Avoid changing too many variables at once, relying on verbal handoffs, or measuring activity without business outcomes. The core actions—${list}—should be documented, visible to the responsible team members, and reviewed after real orders.`] },
      { heading: "Measure and improve", paragraphs: [`Review performance weekly at first. Use a compact scorecard and pair each material variance with one corrective action. Useful measures for this topic include ${topic.metrics.join(", ")}. Trends across several orders are more useful than reacting to one unusual event.`], bullets: topic.metrics.map((metric) => `Track ${metric} consistently and compare it with a defined target`) }
    ],
    faqs: [
      { question: `Why does ${topic.title.toLowerCase()} matter?`, answer: `It helps restaurants connect customer expectations with a repeatable process and sound economics. The exact approach should reflect the restaurant's menu, market, capacity, and service model.` },
      { question: "How quickly should a restaurant implement this?", answer: "A focused first version can often be tested within one to two weeks. Refine it using actual order results before expanding volume or complexity." },
      { question: "What should the team review each week?", answer: `Review ${topic.metrics.join(", ")}, along with customer feedback and operational exceptions. Choose one or two improvements that the team can own during the next cycle.` }
    ]
  };
}

export const scheduledBlogPosts: BlogPost[] = topics.map(makePost);
